version: '3'
services:
  eth-node:
    network_mode: "host"
    image: ethereum/client-go
    volumes:
      - ./data/eth:/root/.ethereum
    command: ["--port", "30303", "--ws", "--ws.addr", "0.0.0.0", "--ws.port", "3334",
      "--http", "--http.api", "eth,net,web3,debug", "--http.addr", "0.0.0.0", "--http.port", "8545", "--http.vhosts", "*",
      "--gcmode", "archive", "--txlookuplimit", "0", "--cache.preimages",  "--rpc.gascap", "0", "--rpc.txfeecap", "0"
      ]
  ipfs:
    network_mode: "host"
    image: ipfs/go-ipfs
      #ports:
      #- '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
    command: ["daemon", "--writable", "--migrate=true", "--agent-version-suffix=docker"]
      #extra_hosts:
      #- "172.18.0.1:host-gateway"
  postgres:
    network_mode: "host"
    image: postgres
      #ports:
      #- '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: eth-graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: eth-graph-node
        #PGDATA: "/data/postgres"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  graph-node:
    image: graph-node
    network_mode: "host"
      #    ports:
      #- '8000:8000'
      #- '8001:8001'
      #- '8020:8020'
      #- '8030:8030'
      #- '8040:8040'
    depends_on:
      - ipfs
      - postgres
      - eth-node
    environment:
      postgres_host: "localhost"
      postgres_user: eth-graph-node
      postgres_pass: let-me-in
      postgres_db: eth-graph-node
      RUST_BACKTRACE: 1
      ipfs: 'localhost:5001'
      ethereum: 'mainnet:http://88.99.195.178:8545'
      ETHEREUM_BLOCK_BATCH_SIZE: 1000
      ETHEREUM_RPC_PARALLEL_REQUESTS: 50000
      GRAPH_LOG: trace
      GRAPH_EXPERIMENTAL_FETCH_TXN_RECEIPTS_CONCURRENTLY: 50000
      GRAPH_ETHEREUM_TARGET_TRIGGERS_PER_BLOCK_RANGE: 1000
      GRAPH_ETHEREUM_BLOCK_INGESTOR_MAX_CONCURRENT_JSON_RPC_CALLS_FOR_TXN_RECEIPTS: 10000
      GRAPH_ETHEREUM_FETCH_TXN_RECEIPTS_IN_BATCHES: "false"
